### ISSUE TITLE
cannot run dmypy-ls after pip-installing to virtualenv

### ISSUE THREAD

**Issue by FelipeLema** [sileht/dmypy-ls#1]
## Expected Behavior
`dmypy-ls` runs

## Actual Behavior
`dmypy-ls` exits with the following error

```
Traceback (most recent call last):
  File "/home/user/dev/venvs/dmypy_ls/bin/dmypy-ls", line 5, in <module>
    from dmypy_ls import main
  File "/home/user/dev/venvs/dmypy_ls/lib/python3.11/site-packages/dmypy_ls/__init__.py", line 36, in <module>
    from pygls.lsp import methods
ImportError: cannot import name 'methods' from 'pygls.lsp' (/home/user/dev/venvs/dmypy_ls/lib/python3.11/site-packages/pygls/lsp/__init__.py)
```

## Steps to Reproduce the Problem

  1. `pypy3 -m venv dmypy_ls`
  2. `source dmypy_ls/bin/activate`
  3. `pip install --upgrade pip dmypy-ls`
  4. `dmypy-ls`

## Specifications

  - Pull Request URL:
  - Mergify Config URL:

**Comment by shosca** [comment]
HTH, this is the way i got it to work with neovim:

- Install from git: `pip install git+https://github.com/sileht/dmypy-ls.git`, pypi package is broken atm
- Package is missing entry point so add this in `__main__.py` right next to `__init__.py` in the venv, 
so something like `<venv path>/lib/python3.x/site-packages/dmypy_ls/__main__.py`
```python
from . import main

main()
```
- Change the `cmd` in the `lspconfig` example to `python -m dmypy_ls`:
```lua
require("lspconfig.configs").dmypyls = {
  default_config = {
    cmd = { "python", "-m", "dmypy_ls" },
    filetypes = { 'python' },
    root_dir = require("lspconfig.util").root_pattern(".git", "pyproject.toml", "setup.py", "setup.cfg"),
    single_file_support = true,
  },
}
```

**Comment by FelipeLema** [comment]
I did as mentioned, plus `pip install lsprotocol mypy pygls` and it seems to be running, but I'm having trouble with stubs: it seems dmypy-ls is not picking MYPYPATH... but I guess I should open a separate issue for that

should the README file be updated with all the info in this conversation?

**Comment by shosca** [comment]
More than that, the package needs to be fixed to have an entry point, should be pretty easy looking at poetry docs:  https://python-poetry.org/docs/pyproject/#scripts

**Comment by dsully** [comment]
FYI, you also need to use the `--chdir` flag so the proper mypy config is picked up.

**Comment by dsully** [comment]
I fixed the script entry point in #2 as well.
